server:
  port: 8000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO



spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://eu-de.appid.cloud.ibm.com/oauth/v4/6a585578-de73-4667-80fc-a4e6501261ac
